AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  pastpricing-backend

  Sample SAM Template for pastpricing-backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 512

Resources:
  PastPricingFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: pastpricing/
      Handler: app.lambdaHandler
      Runtime: nodejs22.x
      Architectures:
      - x86_64
      Events:
        incomingUrlsFifo:
          Type: SQS
          Properties:
              Queue: my queue ;)
              BatchSize: 1
              Enabled: true
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Format: esm
        Minify: false
        OutExtension:
          - .js=.mjs
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
          - app.ts
        External:
        - cheerio
        - nodemailer
        - mongoose
        - axios